---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent
  namespace: default
spec:
  chart:
    spec:
      chart: ./charts/fluent-bit
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: fluent
        namespace: default
  interval: 5m0s
  values:
    envFrom:
      - secretRef: 
          name: fluent-env
    config:
      filters: |
        [FILTER]
            Name kubernetes
            Match kube.*
            Merge_Log On
            Keep_Log Off
            K8S-Logging.Parser On
            K8S-Logging.Exclude On
  
        [FILTER]
          Name grep
          Match *
          Regex $kubernetes['labels']['app'] fluent-bit
      outputs: |
        [OUTPUT]
            Name es                                              
            Match *.*                                            
            Host ${FLUENT_ELASTICSEARCH_HOST}                    
            Port ${FLUENT_ELASTICSEARCH_PORT}                    
            HTTP_Passwd ${FLUENT_ELASTICSEARCH_PASSWD}   
            HTTP_User ${FLUENT_ELASTICSEARCH_USER}       
            Suppress_Type_Name On                        
            Logstash_Format On                           
            Write_Operation upsert                       
            Generate_ID On                               
            Retry_Limit False                            
            tls On                                       
            tls.verify Off                               
            Trace_Error       On                         
            Trace_Output      On                         
            Replace_Dots On
