---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent
  namespace: default
spec:
  chart:
    spec:
      chart: ./charts/fluent-bit
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: fluent
        namespace: default
  interval: 5m0s
  values:
    outputs: |
      [OUTPUT]
        Name es
        Match kube.*
        Host quickstart-es-default 
        Logstash_Format On
        Retry_Limit False

      [OUTPUT]
        Name es
        Match host.*
        Host quickstart-es-default 
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit False
