app:
  name: k8sdiy
  version: v4
  port: 80
image:
  name: denvasyliev/k8sdiy
  tag: build-b1ee187
api:
  replicas: 1
  canary: 0
  header: ""
  port: 8080
ascii:
  replicas: 1
  canary: 0
  header: ""
  port: 8080
img:
  replicas: 1
  canary: 0
  header: ""
  port: 8080
data:
  replicas: 1
  port: 8080
  svc: data
db:
  svc: db
  port: 3306
nats:
  enable: true
  size: 1
  service:
    name: demo-nats
    port: 4222
ns:
  enable: false
api-gateway:
  image:
    tag: 0.51.2
  service:
    type: NodePort
redis:
  architecture: standalone
  auth:
    enabled: false
  service:
    name: redis-master
mysql:
  service:
    name: mysql
