# Source: helm/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: demo
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
---
# Source: helm/charts/mysql/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-mysql
  namespace: demo
  labels:
    service: demo-mysql
spec:
  selector:
    matchLabels:
      app: demo-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-mysql
    spec:
      containers:
      - name: mysql
        image: mysql  # or just image: percona
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        - name: MYSQL_DATABASE
          value: "demo"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3306
